crDroid changes (#8)
* Add Dual SIM audio flags

* Update vendor security patch

* Added camera target flags

* Added more camera flags

* delete one camera flag

* universal7870:  Camera shim fence

* Revert: camera shim fence

Already declarated in fence.cpp

* j7xelte: added wifi display props

* universal7870: Enable Night Mode

* Delete HWC support for Night Light

Due to incompatibility, it makes the screen flashing and systemui crashes

* universal7870: Fix LiveDisplay

* Don't build configstore hal

No needed in Android 10
"Android 10 deprecates the ConfigStore HAL and replaces the HAL with system properties"

* update gralloc header 

Fixes error
frameworks/av/services/camera/libcameraservice/api2/HeicCompositeStream.cpp:328:53: error: use of undeclared identifier 'GRALLOC_USAGE_HW_IMAGE_ENCODER'; did you mean 'GRALLOC_USAGE_HW_VIDEO_ENCODER'?
    (*compositeOutput)[1].consumerUsage = useHeic ? GRALLOC_USAGE_HW_IMAGE_ENCODER :

* Add cpuTempDivider overlay

Co-authored-by: debie-A320FL <79523414+debie-A320FL@users.noreply.github.com>
Co-authored-by: Francesco <60934657+FraSharp@users.noreply.github.com>